name: bootpay_webview_flutter
description: bootpay_webview_flutter 를 국내 결제환경에 맞게 fork 떠서 관리하는 프로젝트 입니다.
repository: https://github.com/bootpay/bootpay_webview_flutter
issue_tracker: https://github.com/bootpay/bootpay_webview_flutter/issues
version: 3.0.13

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: bootpay_webview_flutter_android
      ios:
        default_package: bootpay_webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  bootpay_webview_flutter_android: ^2.8.33
  bootpay_webview_flutter_platform_interface: ^1.8.1
  bootpay_webview_ios: ^2.7.12

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
